substitutions:
  led_pin: GPIO4
  switch_1_relay_pin: GPIO13
  switch_2_relay_pin: GPIO14
  switch_1_button_pin: GPIO16
  switch_2_button_pin: GPIO12

output:
  # 1st gang
  - platform: gpio
    pin: ${switch_1_relay_pin}
    id: relay_1

  # 2nd gang
  - platform: gpio
    pin: ${switch_2_relay_pin}
    id: relay_2

light:
  # Status LED
  - platform: status_led
    name: "Status"
    id: status_light
    pin:
      number: ${led_pin}
      inverted: true

  # 1st gang
  - platform: binary
    name: "1st"
    output: relay_1
    id: light_1

  # 2nd gang
  - platform: binary
    name: "2nd"
    output: relay_2
    id: light_2

binary_sensor:
  # 1st gang
  - platform: gpio
    pin:
      number: ${switch_1_button_pin}
      mode: INPUT
      inverted: true
    name: "1st Button"
    # toggle relay on push
    on_press:
      then:
        - light.toggle: light_1

  # 2nd gang
  - platform: gpio
    pin:
      number: ${switch_2_button_pin}
      mode: INPUT_PULLUP
      inverted: true
    name: "2nd Button"
    # toggle relay on push
    on_press:
      then:
        - light.toggle: light_2
