esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

wifi:
  # Fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"

captive_portal:

logger:

sensor:
  - platform: wifi_signal
    name: ${name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${name} Uptime

switch:
  - platform: restart
    name: "${name} REBOOT"